//! The image pipeline: Dockerfile + guest binary + boot script → deterministic ZIP → S3 →
//! `CreateMicrovmImage`/`UpdateMicrovmImage` (AWS runs the build) → wait for the version.
//!
//! # What is pinned, and what expires anyway
//!
//! The container base is pinned by digest, so the layer we build on cannot move under its tag.
//! The MicroVM base (`al2023-1`, Lambda-managed and mandatory) is **not ours to pin**: AWS
//! deprecates base versions on its own calendar and an image on an EXPIRED base cannot run.
//! [`rebuild_due`] is the expiry check — the SDK does not surface deprecation status directly,
//! so the rule is: **a rebuild is due as soon as our image version's recorded base version is
//! no longer the newest managed base version.** That leads AWS's deprecation clock (60 d
//! DEPRECATED + 30 d EXPIRING) rather than racing it.

use std::io::Write as _;
use std::time::Duration;

use anyhow::{Context as _, bail};
use aws_sdk_lambdamicrovms::types::{
    Architecture, Capability, CloudWatchLogging, CodeArtifact, CpuConfiguration, HookState, Hooks,
    Logging, MicrovmHooks, MicrovmImageHooks, MicrovmImageVersionState, Resources,
};
use sha2::Digest as _;

use crate::AGENT_PORT;
use crate::control::Control;

/// The container base, pinned by digest (resolved from public ECR on 2026-08-18). A tag is a
/// moving reference; a digest is the bytes. Public ECR rather than Docker Hub because the AWS
/// build environment pulls anonymously and Docker Hub throttles anonymous pulls from AWS IPs.
pub const CONTAINER_BASE: &str = "public.ecr.aws/ubuntu/ubuntu:24.04@sha256:a54764b5b6340c272ffb45e303fe4c8064bbdfb76d732b325b79ae6b92900e4c";

/// The JavaScript runtime used by deployable Brain tools. The MicroVM image is ARM64-only, so
/// its archive digest can be pinned directly. Keep the plain-Docker image's ARM64 pin in sync.
pub const NODE_VERSION: &str = "22.23.2";
pub const NODE_ARM64_SHA256: &str =
    "fff4078c5def658577f92c88db7db3bc0072924bfb93fe52c1e744a54e94abb8";
/// Patched npm replacing the vulnerable copy bundled with the pinned Node archive.
pub const NPM_VERSION: &str = "11.19.0";

/// The Lambda-managed MicroVM base every image must sit on.
pub fn base_image_arn(region: &str) -> String {
    format!("arn:aws:lambda:{region}:aws:microvm-image:al2023-1")
}

/// Fixed ZIP entry timestamp (2026-08-01T00:00:00Z) so the artifact digest is a function of
/// its contents, not of the build clock.
fn zip_time() -> zip::DateTime {
    zip::DateTime::from_date_and_time(2026, 8, 1, 0, 0, 0).expect("valid constant timestamp")
}

/// The in-guest DNS resolver. The MicroVM blocks outbound UDP, which breaks ordinary
/// resolv.conf entries; this AWS-provided address answers inside the VM.
pub const GUEST_DNS: &str = "169.254.169.253";

/// Default swap: 2 GiB, created and enabled at boot so memory pressure turns "job failed" into
/// "job was slow". Boot continues if `swapon` is refused; the swap probe records the outcome.
pub const DEFAULT_SWAP_BYTES: u64 = 2 * 1024 * 1024 * 1024;
/// The only hosted alpha MicroVM shape. Capacity accounting in the production Hand consumes this
/// same constant, so image publication cannot expose an operator-selected physical memory size.
pub const MVP_TARGET_MEMORY_MIB: u32 = 1_024;

/// The boot script: root sets up DNS and swap, then drops to the dedicated Hand supervisor. The
/// supervisor binary has only kill/setuid/setgid capability and irreversibly drops Tool children
/// to `agent`; arbitrary code never shares the control UID. `CAP_KILL` is required because Linux
/// does not grant a parent a special right to signal a child after that child changes to UID 1000.
#[must_use]
pub fn boot_script() -> String {
    format!(
        r#"#!/bin/sh
# Generated by hand-lambda. Runs as root, drops to the Hand supervisor.
set -eu
printf 'nameserver {GUEST_DNS}\n' > /etc/resolv.conf || true
# The provider listener is host-reachable but must not be a control socket for any Tool uid. A
# background Tool also cannot impersonate the endpoint after a supervisor crash: response packets
# sourced from the control port are supervisor-only.
nft add table inet aex_hand
nft 'add chain inet aex_hand output {{ type filter hook output priority 0; policy accept; }}'
nft add rule inet aex_hand output tcp sport {AGENT_PORT} meta skuid != 1001 reject
nft add rule inet aex_hand output oifname "lo" tcp dport {AGENT_PORT} meta skuid != 1001 reject
for address in $(ip -o -4 address show | awk '{{print $4}}' | cut -d/ -f1); do
  nft add rule inet aex_hand output ip daddr "$address"/32 tcp dport {AGENT_PORT} meta skuid != 1001 reject
done
if [ -w /proc/sys/kernel/unprivileged_userns_clone ]; then
  printf '0\n' > /proc/sys/kernel/unprivileged_userns_clone
fi
if [ -w /proc/sys/user/max_user_namespaces ]; then
  printf '0\n' > /proc/sys/user/max_user_namespaces
fi
ulimit -c 0
# Engine-created workspace directories and ordinary Tool output share the workspace group. An
# explicit mode-0600 file remains binding-private until its owner deliberately changes the mode.
umask 0002
swap_bytes="${{HAND_SWAP_BYTES:-{DEFAULT_SWAP_BYTES}}}"
if [ "$swap_bytes" -gt 0 ] 2>/dev/null; then
  if [ ! -f /swapfile ]; then
    fallocate -l "$swap_bytes" /swapfile 2>/dev/null \
      || dd if=/dev/zero of=/swapfile bs=1M count=$((swap_bytes / 1048576)) 2>/dev/null || true
    chmod 600 /swapfile 2>/dev/null || true
    mkswap /swapfile >/dev/null 2>&1 || true
  fi
  swapon /swapfile 2>&1 || echo "aex-boot: swapon failed" >&2
fi
exec setpriv --reuid hand --regid hand --init-groups \
  env HOME=/home/agent USER=hand LOGNAME=hand /usr/local/bin/hand-guest
"#
    )
}

/// The generated Dockerfile for the Lambda image. Mirrors `image/Dockerfile` (the plain-Docker
/// dev image) with the Lambda differences: pinned base, boot script entrypoint (root → swap +
/// DNS → dedicated supervisor), port 8080 only.
#[must_use]
pub fn dockerfile() -> String {
    format!(
        r#"# Generated by hand-lambda. Do not edit: change hand-lambda's image module instead.
FROM {CONTAINER_BASE}

ENV DEBIAN_FRONTEND=noninteractive \
    LANG=C.UTF-8 \
    HOME=/home/agent \
    CARGO_HOME=/workspace/.hand/cargo \
    RUSTUP_HOME=/workspace/.hand/rustup \
    GOPATH=/workspace/.hand/go \
    GOMODCACHE=/workspace/.hand/go/pkg/mod \
    npm_config_prefix=/workspace/.hand/npm \
    PIP_CACHE_DIR=/workspace/.hand/pip \
    PIPX_HOME=/workspace/.hand/pipx \
    PIPX_BIN_DIR=/workspace/.hand/bin \
    UV_CACHE_DIR=/workspace/.hand/uv \
    PATH=/workspace/.hand/bin:/workspace/.hand/npm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    HAND_WORKSPACE=/workspace \
    HAND_TOOL_DIR=/var/hand/tools \
    HAND_TOOL_RUNNER=/usr/local/lib/hand/tool-runner.mjs \
    HAND_TOOL_BOUNDARY_LIBRARY=/usr/local/lib/hand/tool-boundary.so \
    HAND_SUPERVISOR_UID=1001 \
    HAND_TOOL_UID=1000 \
    HAND_TOOL_GID=1000 \
    HAND_LISTEN=0.0.0.0:{AGENT_PORT}

RUN apt-get update && apt-get install -y --no-install-recommends \
      ca-certificates curl wget git openssh-client \
      build-essential pkg-config \
      python3 python3-venv python3-pip pipx \
      ripgrep jq unzip zip zstd xz-utils file less \
      procps coreutils bash libcap2-bin util-linux iproute2 nftables \
    && rm -rf /var/lib/apt/lists/* \
    && curl --fail --location --retry 5 \
         --output /tmp/node.tar.xz \
         "https://nodejs.org/dist/v{NODE_VERSION}/node-v{NODE_VERSION}-linux-arm64.tar.xz" \
    && echo "{NODE_ARM64_SHA256}  /tmp/node.tar.xz" | sha256sum --check --strict \
    && tar --extract --file /tmp/node.tar.xz --directory /usr/local --strip-components=1 \
    && rm /tmp/node.tar.xz \
    && test "$(node --version)" = "v{NODE_VERSION}" \
    && npm_config_prefix=/usr/local npm install --global npm@{NPM_VERSION} \
    && test "$(npm --version)" = "{NPM_VERSION}"

# ubuntu:24.04 ships a uid-1000 "ubuntu" user; remove it, then create "agent" as uid 1000.
RUN deluser --remove-home ubuntu 2>/dev/null || true; \
    userdel -f ubuntu 2>/dev/null || true; \
    groupdel ubuntu 2>/dev/null || true; \
    useradd --create-home --home-dir /home/agent --shell /bin/bash --uid 1000 --user-group agent \
    && groupadd --gid 1001 hand \
    && useradd --uid 1001 --gid hand --groups agent --no-create-home --home-dir /nonexistent hand \
    && mkdir -p /workspace /var/hand/ops /var/hand/bindings /var/hand/objects /var/hand/file-staging /var/hand/tools /usr/local/lib/hand \
    && chown -R agent:agent /workspace /home/agent \
    && chmod 2770 /workspace /home/agent \
    && chown -R hand:hand /var/hand/ops /var/hand/bindings /var/hand/objects \
    && chmod 0700 /var/hand/ops /var/hand/bindings /var/hand/objects \
    && chown -R hand:agent /var/hand/file-staging \
    && chmod 2700 /var/hand/file-staging \
    && chown -R hand:agent /var/hand/tools \
    && chmod 2750 /var/hand/tools \
    && test "$(stat -c '%d:%g' /workspace)" = "$(stat -c '%d:%g' /var/hand/file-staging)" \
    && test "$(stat -c '%a' /var/hand/file-staging)" = 2700

# No Tool-visible package may retain a privilege transition. The only file capability added back
    # is the dedicated Hand supervisor executable below.
RUN find / -xdev -type f -perm /6000 -exec chmod a-s {{}} + \
    && getcap -r /usr /bin /sbin /usr/local 2>/dev/null \
         | awk '{{print $1}}' | sort -u | xargs -r -n1 setcap -r

COPY --chmod=0755 hand-guest /usr/local/bin/hand-guest
COPY --chmod=0755 hand-boot.sh /usr/local/bin/hand-boot.sh
COPY --chmod=0644 tool-runner.mjs /usr/local/lib/hand/tool-runner.mjs
COPY --chmod=0644 tool-boundary.c /tmp/tool-boundary.c
COPY --chmod=0644 proc-secret-static.c /tmp/proc-secret-static.c

RUN chown root:hand /usr/local/bin/hand-guest \
    && chmod 0750 /usr/local/bin/hand-guest \
    && cc -shared -fPIC -O2 -Wl,-z,relro,-z,now \
         -o /usr/local/lib/hand/tool-boundary.so /tmp/tool-boundary.c \
    && cc -static -O2 -Wl,-z,relro,-z,now \
         -o /usr/local/lib/hand/proc-secret-static /tmp/proc-secret-static.c \
    && rm /tmp/tool-boundary.c /tmp/proc-secret-static.c \
    && chown root:root /usr/local/lib/hand/tool-boundary.so /usr/local/lib/hand/proc-secret-static \
    && chmod 0555 /usr/local/lib/hand/tool-boundary.so /usr/local/lib/hand/proc-secret-static \
    && setcap cap_kill,cap_setuid,cap_setgid=ep /usr/local/bin/hand-guest \
    && test "$(stat -c '%u:%g:%a' /usr/local/lib/hand/tool-boundary.so)" = "0:0:555" \
    && test "$(stat -c '%u:%g:%a' /usr/local/lib/hand/proc-secret-static)" = "0:0:555" \
    && ! readelf -l /usr/local/lib/hand/proc-secret-static | grep -q INTERP \
    && test -z "$(find / -xdev -type f -perm /6000 -print -quit)" \
    && test "$(getcap -r / 2>/dev/null)" = "/usr/local/bin/hand-guest cap_kill,cap_setgid,cap_setuid=ep"

# Root on purpose: the boot script pins DNS and enables swap, then setprivs down to the supervisor.
WORKDIR /workspace
EXPOSE {AGENT_PORT}
ENTRYPOINT ["/usr/local/bin/hand-boot.sh"]
"#
    )
}

/// Packs the build context: image recipe, boot/runner scripts, and the aarch64 guest binary.
/// Deterministic: fixed entry order, fixed timestamps — the same inputs give byte-identical
/// ZIPs, so the S3 key (content hash) is stable across rebuilds.
pub fn pack_zip(guest_binary: &[u8]) -> anyhow::Result<Vec<u8>> {
    let mut zw = zip::ZipWriter::new(std::io::Cursor::new(Vec::new()));
    let file = |mode: u32| {
        zip::write::SimpleFileOptions::default()
            .compression_method(zip::CompressionMethod::Deflated)
            .last_modified_time(zip_time())
            .unix_permissions(mode)
    };
    zw.start_file("Dockerfile", file(0o644))?;
    zw.write_all(dockerfile().as_bytes())?;
    zw.start_file("hand-boot.sh", file(0o755))?;
    zw.write_all(boot_script().as_bytes())?;
    zw.start_file("hand-guest", file(0o755))?;
    zw.write_all(guest_binary)?;
    zw.start_file("tool-runner.mjs", file(0o644))?;
    zw.write_all(include_bytes!("../../../image/tool-runner.mjs"))?;
    zw.start_file("tool-boundary.c", file(0o644))?;
    zw.write_all(include_bytes!("../../../image/tool-boundary.c"))?;
    zw.start_file("proc-secret-static.c", file(0o644))?;
    zw.write_all(include_bytes!("../../../image/proc-secret-static.c"))?;
    Ok(zw.finish()?.into_inner())
}

/// Where a packed context lives in the artifact bucket.
#[must_use]
pub fn artifact_key(zip: &[u8]) -> String {
    let sha = hex::encode(sha2::Sha256::digest(zip));
    format!("hands/images/{sha}.zip")
}

/// Everything `publish` needs besides the bytes.
#[derive(Debug, Clone)]
pub struct PublishConfig {
    /// Image name (one per shape variant), e.g. `hands-dev-1gb`.
    pub name: String,
    /// S3 bucket the ZIP is uploaded to.
    pub bucket: String,
    /// IAM role the build assumes to read the ZIP.
    pub build_role_arn: String,
    /// CloudWatch log group for build output.
    pub log_group: String,
    /// Exact plane-owned connector ARNs accepted by the release. `RunMicrovm` selects one sealed
    /// class for each generation; the image build itself uses one AWS-managed connector.
    pub egress_connectors: Vec<String>,
}

/// The published outcome: what `RunMicrovm` needs.
#[derive(Debug, Clone)]
pub struct PublishedImage {
    pub image_arn: String,
    pub image_version: String,
}

/// Bump this whenever a fixed `CreateMicrovmImage`/`UpdateMicrovmImage` request field changes.
/// Variable request fields are hashed individually below.
const PUBLISH_REQUEST_TOKEN_SCHEMA: &str = "hand-lambda-publish-request-v4";

#[derive(Clone, Copy)]
enum PublishOperation {
    Create,
    Update,
}

impl PublishOperation {
    const fn as_str(self) -> &'static str {
        match self {
            Self::Create => "create",
            Self::Update => "update",
        }
    }
}

/// AWS treats a client token as an idempotency key for the complete API request, not merely the
/// uploaded bytes. Hash every variable request identity field and the validated runtime connector
/// policy with unambiguous length prefixes. The schema marker represents the fixed fields (hooks,
/// ARM64, image-build internet egress, and capabilities).
fn publish_client_token(
    operation: PublishOperation,
    region: &str,
    image_identifier: &str,
    cfg: &PublishConfig,
    artifact_key: &str,
) -> String {
    let mut digest = sha2::Sha256::new();
    for field in [
        PUBLISH_REQUEST_TOKEN_SCHEMA,
        operation.as_str(),
        region,
        image_identifier,
        &cfg.name,
        &cfg.bucket,
        &cfg.build_role_arn,
        &cfg.log_group,
        artifact_key,
    ] {
        digest.update((field.len() as u64).to_be_bytes());
        digest.update(field.as_bytes());
    }
    let mut connectors = cfg.egress_connectors.clone();
    connectors.sort();
    for connector in connectors {
        digest.update((connector.len() as u64).to_be_bytes());
        digest.update(connector.as_bytes());
    }
    hex::encode(&digest.finalize()[..16])
}

pub fn validate_network_connector_arn(connector: &str, region: &str) -> anyhow::Result<()> {
    let mut parts = connector.split(':');
    let fixed = ["arn", "aws", "lambda", region];
    for expected in fixed {
        anyhow::ensure!(
            parts.next() == Some(expected),
            "invalid network connector ARN"
        );
    }
    let account = parts.next().unwrap_or_default();
    anyhow::ensure!(
        account.len() == 12 && account.bytes().all(|byte| byte.is_ascii_digit()),
        "invalid network connector ARN"
    );
    anyhow::ensure!(
        parts.next() == Some("network-connector"),
        "invalid network connector ARN"
    );
    let name = parts.next().unwrap_or_default();
    anyhow::ensure!(
        !name.is_empty()
            && name.len() <= 64
            && name
                .bytes()
                .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_')),
        "invalid network connector ARN"
    );
    if let Some(version) = parts.next() {
        anyhow::ensure!(
            !version.is_empty()
                && version.bytes().all(|byte| byte.is_ascii_digit())
                && version != "0",
            "invalid network connector ARN"
        );
    }
    anyhow::ensure!(parts.next().is_none(), "invalid network connector ARN");
    Ok(())
}

fn validated_connectors(connectors: &[String], region: &str) -> anyhow::Result<Vec<String>> {
    let mut connectors = connectors.to_vec();
    connectors.sort();
    connectors.dedup();
    anyhow::ensure!(
        connectors.len() == 3,
        "image publication requires three distinct plane-owned egress connector ARNs"
    );
    for connector in &connectors {
        validate_network_connector_arn(connector, region)?;
    }
    Ok(connectors)
}

fn image_build_egress_connector(region: &str) -> String {
    format!("arn:aws:lambda:{region}:aws:network-connector:aws-network-connector:INTERNET_EGRESS")
}

/// Uploads the context and registers a new image (or a new version of an existing one), then
/// waits for AWS's build to finish. Idempotent by exact publish request: the client token includes
/// the artifact digest and all plane-specific request identity.
pub async fn publish(
    control: &Control,
    s3: &aws_sdk_s3::Client,
    cfg: &PublishConfig,
    zip: Vec<u8>,
) -> anyhow::Result<PublishedImage> {
    validated_connectors(&cfg.egress_connectors, control.region())?;
    let image_build_egress = image_build_egress_connector(control.region());
    let key = artifact_key(&zip);
    let uri = format!("s3://{}/{key}", cfg.bucket);
    s3.put_object()
        .bucket(&cfg.bucket)
        .key(&key)
        .body(aws_sdk_s3::primitives::ByteStream::from(zip))
        .send()
        .await
        .context("uploading image context to S3")?;
    tracing::info!(%uri, "context uploaded");

    let hooks = Hooks::builder()
        .port(i32::from(AGENT_PORT))
        .microvm_hooks(
            MicrovmHooks::builder()
                .run(HookState::Enabled)
                .run_timeout_in_seconds(60)
                // These hook requests carry no application authentication and arrive on the
                // guest-visible listener. Resume needs no mutation; shutdown is external; and
                // sandbox persistence is never implicit.
                .resume(HookState::Disabled)
                .suspend(HookState::Disabled)
                .terminate(HookState::Disabled)
                .build(),
        )
        .microvm_image_hooks(
            MicrovmImageHooks::builder()
                .ready(HookState::Enabled)
                .ready_timeout_in_seconds(300)
                .validate(HookState::Enabled)
                .validate_timeout_in_seconds(120)
                .build(),
        )
        .build();
    let logging = Logging::CloudWatch(
        CloudWatchLogging::builder()
            .log_group(&cfg.log_group)
            .log_stream(&cfg.name)
            .build(),
    );
    let sdk = control.sdk();
    let exists = find_image_arn(control, &cfg.name).await?;

    let arn = if let Some(arn) = exists {
        let client_token =
            publish_client_token(PublishOperation::Update, control.region(), &arn, cfg, &key);
        sdk.update_microvm_image()
            .image_identifier(&arn)
            .base_image_arn(base_image_arn(control.region()))
            .build_role_arn(&cfg.build_role_arn)
            .description(format!("Hand guest ({MVP_TARGET_MEMORY_MIB} MiB shape)"))
            .code_artifact(CodeArtifact::Uri(uri))
            .logging(logging)
            .egress_network_connectors(image_build_egress.clone())
            .cpu_configurations(
                CpuConfiguration::builder()
                    .architecture(Architecture::Arm64)
                    .build()
                    .context("cpu configuration")?,
            )
            .resources(
                Resources::builder()
                    .minimum_memory_in_mib(MVP_TARGET_MEMORY_MIB as i32)
                    .build()
                    .context("resources")?,
            )
            .additional_os_capabilities(Capability::All)
            .hooks(hooks)
            .client_token(&client_token)
            .send()
            .await
            .map_err(|e| anyhow::anyhow!("update_microvm_image: {}", detail(&e)))?;
        arn
    } else {
        let client_token = publish_client_token(
            PublishOperation::Create,
            control.region(),
            &cfg.name,
            cfg,
            &key,
        );
        let out = sdk
            .create_microvm_image()
            .name(&cfg.name)
            .base_image_arn(base_image_arn(control.region()))
            .build_role_arn(&cfg.build_role_arn)
            .description(format!("Hand guest ({MVP_TARGET_MEMORY_MIB} MiB shape)"))
            .code_artifact(CodeArtifact::Uri(uri))
            .logging(logging)
            .egress_network_connectors(image_build_egress)
            .cpu_configurations(
                CpuConfiguration::builder()
                    .architecture(Architecture::Arm64)
                    .build()
                    .context("cpu configuration")?,
            )
            .resources(
                Resources::builder()
                    .minimum_memory_in_mib(MVP_TARGET_MEMORY_MIB as i32)
                    .build()
                    .context("resources")?,
            )
            .additional_os_capabilities(Capability::All)
            .hooks(hooks)
            .client_token(&client_token)
            .send()
            .await
            .map_err(|e| anyhow::anyhow!("create_microvm_image: {}", detail(&e)))?;
        out.image_arn().to_owned()
    };
    tracing::info!(%arn, "image registration accepted; AWS is building");
    wait_for_build(control, &arn).await
}

/// Polls until the newest version of `image_arn` leaves PENDING/IN_PROGRESS. AWS's builds run
/// minutes, not seconds; the timeout is generous and the caller sees every transition.
pub async fn wait_for_build(control: &Control, image_arn: &str) -> anyhow::Result<PublishedImage> {
    let deadline = tokio::time::Instant::now() + Duration::from_secs(30 * 60);
    let sdk = control.sdk();
    loop {
        let out = sdk
            .list_microvm_image_versions()
            .image_identifier(image_arn)
            .send()
            .await
            .map_err(|e| anyhow::anyhow!("list_microvm_image_versions: {}", detail(&e)))?;
        let newest = out
            .items()
            .iter()
            .max_by_key(|v| version_ord(v.image_version()))
            .context("image has no versions")?;
        let version = newest.image_version().to_owned();
        match newest.state() {
            MicrovmImageVersionState::Successful => {
                tracing::info!(%version, "image version built");
                return Ok(PublishedImage {
                    image_arn: image_arn.to_owned(),
                    image_version: version,
                });
            }
            MicrovmImageVersionState::Failed => {
                bail!(
                    "image version {version} failed: {}",
                    newest.state_reason().unwrap_or("no reason given")
                );
            }
            state => {
                tracing::info!(%version, ?state, "building…");
            }
        }
        if tokio::time::Instant::now() > deadline {
            bail!("image build did not finish within 30 minutes");
        }
        tokio::time::sleep(Duration::from_secs(15)).await;
    }
}

/// Whether the image version needs rebuilding: its recorded MicroVM base version is no longer
/// the newest managed base version (AWS retires old bases on its own schedule).
pub async fn rebuild_due(
    control: &Control,
    image_arn: &str,
    image_version: &str,
) -> anyhow::Result<Option<String>> {
    let sdk = control.sdk();
    let ours = sdk
        .get_microvm_image_version()
        .image_identifier(image_arn)
        .image_version(image_version)
        .send()
        .await
        .map_err(|e| anyhow::anyhow!("get_microvm_image_version: {}", detail(&e)))?;
    let base_arn = ours.base_image_arn().to_owned();
    let our_base = ours.base_image_version().unwrap_or("0").to_owned();
    let managed = sdk
        .list_managed_microvm_image_versions()
        .image_identifier(&base_arn)
        .send()
        .await
        .map_err(|e| anyhow::anyhow!("list_managed_microvm_image_versions: {}", detail(&e)))?;
    let newest = managed
        .items()
        .iter()
        .map(|v| v.image_version().to_owned())
        .max_by_key(|v| version_ord(v));
    match newest {
        Some(newest) if version_ord(&newest) > version_ord(&our_base) => Ok(Some(newest)),
        _ => Ok(None),
    }
}

/// Orders version strings like `3.0` numerically, not lexically (so `10.0` > `9.0`).
fn version_ord(v: &str) -> (u64, u64) {
    let mut parts = v.split('.');
    let major = parts.next().and_then(|p| p.parse().ok()).unwrap_or(0);
    let minor = parts.next().and_then(|p| p.parse().ok()).unwrap_or(0);
    (major, minor)
}

/// The ARN of the image named `name`, if it exists. Accepts an ARN and returns it unchanged.
pub async fn find_image_arn(control: &Control, name: &str) -> anyhow::Result<Option<String>> {
    if name.starts_with("arn:") {
        return Ok(Some(name.to_owned()));
    }
    let mut next: Option<String> = None;
    loop {
        let out = control
            .sdk()
            .list_microvm_images()
            .set_next_token(next)
            .send()
            .await
            .map_err(|e| anyhow::anyhow!("list_microvm_images: {}", detail(&e)))?;
        for item in out.items() {
            if item.name() == name {
                return Ok(Some(item.image_arn().to_owned()));
            }
        }
        next = out.next_token().map(str::to_owned);
        if next.is_none() {
            return Ok(None);
        }
    }
}

/// Grumble: `SdkError` Display hides the service message; this pulls it out.
fn detail<E: ProvideErrorMetadataExt, R>(
    e: &aws_sdk_lambdamicrovms::error::SdkError<E, R>,
) -> String {
    match e {
        aws_sdk_lambdamicrovms::error::SdkError::ServiceError(s) => format!(
            "{}: {}",
            s.err().code().unwrap_or("service error"),
            s.err().message().unwrap_or("no message")
        ),
        other => other.to_string(),
    }
}

/// Alias so the helpers stay generic over every operation's error type.
pub trait ProvideErrorMetadataExt: aws_sdk_lambdamicrovms::error::ProvideErrorMetadata {}
impl<T: aws_sdk_lambdamicrovms::error::ProvideErrorMetadata> ProvideErrorMetadataExt for T {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_zip_is_deterministic_and_contains_exactly_the_context() {
        let a = pack_zip(b"binary-bytes").unwrap();
        let b = pack_zip(b"binary-bytes").unwrap();
        assert_eq!(a, b, "same inputs must give byte-identical ZIPs");
        let mut ar = zip::ZipArchive::new(std::io::Cursor::new(a)).unwrap();
        let names: Vec<String> = (0..ar.len())
            .map(|i| ar.by_index(i).unwrap().name().to_owned())
            .collect();
        assert_eq!(
            names,
            vec![
                "Dockerfile",
                "hand-boot.sh",
                "hand-guest",
                "tool-runner.mjs",
                "tool-boundary.c",
                "proc-secret-static.c"
            ]
        );
        let c = pack_zip(b"other-binary").unwrap();
        assert_ne!(artifact_key(&b), artifact_key(&c));
    }

    fn publish_config(name: &str) -> PublishConfig {
        PublishConfig {
            name: name.to_owned(),
            bucket: "artifacts-dev".to_owned(),
            build_role_arn: "arn:aws:iam::111111111111:role/build-dev".to_owned(),
            log_group: "/aex/dev/hands-build".to_owned(),
            egress_connectors: vec![
                "arn:aws:lambda:us-east-1:111111111111:network-connector:allowlist".into(),
                "arn:aws:lambda:us-east-1:111111111111:network-connector:none".into(),
                "arn:aws:lambda:us-east-1:111111111111:network-connector:public".into(),
            ],
        }
    }

    #[test]
    fn publish_token_is_stable_for_the_same_exact_request() {
        let cfg = publish_config("hands-dev-1gb");
        let key = artifact_key(b"same image");
        let token = publish_client_token(
            PublishOperation::Update,
            "eu-west-2",
            "arn:aws:lambda:eu-west-2:111111111111:microvm-image:hands-dev-1gb",
            &cfg,
            &key,
        );
        assert_eq!(
            token,
            publish_client_token(
                PublishOperation::Update,
                "eu-west-2",
                "arn:aws:lambda:eu-west-2:111111111111:microvm-image:hands-dev-1gb",
                &cfg,
                &key,
            )
        );
    }

    #[test]
    fn image_build_uses_one_provider_connector_while_runtime_policy_keeps_all_three() {
        let cfg = publish_config("hands-dev-1gb");
        assert_eq!(
            validated_connectors(&cfg.egress_connectors, "us-east-1")
                .unwrap()
                .len(),
            3
        );
        assert_eq!(
            image_build_egress_connector("us-east-1"),
            "arn:aws:lambda:us-east-1:aws:network-connector:aws-network-connector:INTERNET_EGRESS"
        );
    }

    #[test]
    fn publish_token_separates_planes_and_request_parameters() {
        let dev = publish_config("hands-dev-1gb");
        let mut prd = dev.clone();
        prd.name = "hands-prd-1gb".to_owned();
        prd.bucket = "artifacts-prd".to_owned();
        prd.build_role_arn = "arn:aws:iam::222222222222:role/build-prd".to_owned();
        prd.log_group = "/aex/prd/hands-build".to_owned();
        let key = artifact_key(b"same image");
        let dev_token = publish_client_token(
            PublishOperation::Update,
            "eu-west-2",
            "arn:aws:lambda:eu-west-2:111111111111:microvm-image:hands-dev-1gb",
            &dev,
            &key,
        );
        let prd_token = publish_client_token(
            PublishOperation::Update,
            "eu-west-2",
            "arn:aws:lambda:eu-west-2:222222222222:microvm-image:hands-prd-1gb",
            &prd,
            &key,
        );
        assert_ne!(dev_token, prd_token);
    }

    #[test]
    fn publish_token_changes_when_any_request_identity_changes() {
        let cfg = publish_config("hands-dev-1gb");
        let key = artifact_key(b"image a");
        let target = "arn:aws:lambda:eu-west-2:111111111111:microvm-image:hands-dev-1gb";
        let token = publish_client_token(PublishOperation::Update, "eu-west-2", target, &cfg, &key);

        let variants = [
            publish_client_token(PublishOperation::Create, "eu-west-2", target, &cfg, &key),
            publish_client_token(PublishOperation::Update, "us-east-1", target, &cfg, &key),
            publish_client_token(
                PublishOperation::Update,
                "eu-west-2",
                "different-target",
                &cfg,
                &key,
            ),
            publish_client_token(
                PublishOperation::Update,
                "eu-west-2",
                target,
                &cfg,
                &artifact_key(b"image b"),
            ),
        ];
        for variant in variants {
            assert_ne!(token, variant);
        }

        let config_variants = [
            PublishConfig {
                name: "different-name".to_owned(),
                ..cfg.clone()
            },
            PublishConfig {
                bucket: "different-bucket".to_owned(),
                ..cfg.clone()
            },
            PublishConfig {
                build_role_arn: "different-role".to_owned(),
                ..cfg.clone()
            },
            PublishConfig {
                log_group: "different-log-group".to_owned(),
                ..cfg.clone()
            },
            PublishConfig {
                egress_connectors: vec![
                    "arn:aws:lambda:us-east-1:111111111111:network-connector:allowlist".into(),
                    "arn:aws:lambda:us-east-1:111111111111:network-connector:none".into(),
                    "arn:aws:lambda:us-east-1:111111111111:network-connector:other-public".into(),
                ],
                ..cfg.clone()
            },
        ];
        for changed in config_variants {
            assert_ne!(
                token,
                publish_client_token(
                    PublishOperation::Update,
                    "eu-west-2",
                    target,
                    &changed,
                    &key,
                )
            );
        }
    }

    #[test]
    fn the_dockerfile_is_pinned_and_serves_one_port_as_root_boot() {
        assert_eq!(MVP_TARGET_MEMORY_MIB, 1_024);
        let df = dockerfile();
        assert!(df.contains("@sha256:"), "base must be digest-pinned");
        assert!(df.contains("EXPOSE 8080"));
        assert!(df.contains(&format!("node-v{NODE_VERSION}-linux-arm64.tar.xz")));
        assert!(df.contains(NODE_ARM64_SHA256));
        assert!(df.contains(&format!(r#"test "$(node --version)" = "v{NODE_VERSION}""#)));
        assert!(df.contains(&format!("npm@{NPM_VERSION}")));
        assert!(df.contains(&format!(r#"test "$(npm --version)" = "{NPM_VERSION}""#)));
        assert!(
            !df.contains("\nUSER "),
            "the boot script drops privileges; the Dockerfile must not"
        );
        assert!(df.contains(r#"ENTRYPOINT ["/usr/local/bin/hand-boot.sh"]"#));
    }

    #[test]
    fn the_boot_script_pins_dns_and_drops_to_the_supervisor() {
        let boot = boot_script();
        let df = dockerfile();
        assert!(boot.contains(GUEST_DNS));
        assert!(boot.contains("setpriv --reuid hand"));
        assert!(boot.contains("meta skuid != 1001"));
        assert!(boot.contains(&format!("tcp dport {AGENT_PORT}")));
        assert!(boot.contains(&format!("tcp sport {AGENT_PORT}")));
        assert!(!boot.contains("iptables"));
        assert!(boot.contains("unprivileged_userns_clone"));
        assert!(boot.contains("max_user_namespaces"));
        assert!(boot.contains("ulimit -c 0"));
        assert!(boot.contains("umask 0002"));
        assert!(df.contains("setcap cap_kill,cap_setuid,cap_setgid=ep"));
        assert!(df.contains("cc -static -O2"));
        assert!(
            df.contains("! readelf -l /usr/local/lib/hand/proc-secret-static | grep -q INTERP")
        );
        assert!(df.contains("find / -xdev -type f -perm /6000 -print -quit"));
        assert!(df.contains(
            "getcap -r / 2>/dev/null)\" = \"/usr/local/bin/hand-guest cap_kill,cap_setgid,cap_setuid=ep"
        ));
        assert!(df.contains("find / -xdev -type f -perm /6000 -exec chmod a-s {} +"));
        assert!(df.contains("xargs -r -n1 setcap -r"));
        assert!(df.contains("/var/hand/file-staging"));
        assert!(df.contains(r#"stat -c '%d:%g' /workspace"#));
        assert!(df.contains(r#"stat -c '%a' /var/hand/file-staging)" = 2700"#));
        assert!(boot.contains("swapon"));
    }

    #[test]
    fn versions_order_numerically() {
        assert!(version_ord("10.0") > version_ord("9.0"));
        assert!(version_ord("3.1") > version_ord("3.0"));
        assert_eq!(version_ord("junk"), (0, 0));
    }

    #[test]
    fn connector_arns_follow_the_lambda_core_service_shape() {
        assert!(
            validate_network_connector_arn(
                "arn:aws:lambda:us-east-1:111111111111:network-connector:aex-dev-none",
                "us-east-1"
            )
            .is_ok()
        );
        assert!(
            validate_network_connector_arn(
                "arn:aws:lambda:us-east-1:111111111111:network-connector:aex-dev-none:2",
                "us-east-1"
            )
            .is_ok()
        );
        for connector in [
            "arn:aws:lambda:eu-west-1:111111111111:network-connector:aex-dev-none",
            "arn:aws:lambda:us-east-1:111111111111:network-connector/aex-dev-none",
            "arn:aws:lambda:us-east-1:111:network-connector:aex-dev-none",
            "arn:aws:lambda:us-east-1:111111111111:network-connector:aex-dev-none:0",
        ] {
            assert!(
                validate_network_connector_arn(connector, "us-east-1").is_err(),
                "{connector}"
            );
        }
    }
}
